import React from "react"
import ReactDOM from "react-dom"
import "./tailwind.output.css" // Autogenerated
import NewHeader from "./components/NewHeader"
import Ticker from "./components/Ticker"
import Content from "./components/Content"

const App = () => {
  return (
    <div>
      <NewHeader />
      <Ticker />
      <Content />
    </div>
  )
}

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
