import React, { useState, useEffect } from "react"
import ReactDOM from "react-dom"
import "./tailwind.output.css" // Autogenerated
import Header from "./components/Header"
import Ticker from "./components/Ticker"
import Content from "./components/Content"

const App = () => {
  const [chartData, setChartData] = useState([])

  const queryResultCallBack = (ticker) => {
    fetch(
      `https://api.tdameritrade.com/v1/marketdata/${ticker}/pricehistory?periodType=month&period=6&frequencyType=daily&frequency=1&needExtendedHoursData=false`,
      {
        headers: new Headers({
          Authorization: `Bearer ${process.env.REACT_APP_ACCESS_TOKEN}`,
        }),
      }
    )
      .then((res) => res.json())
      .then((res) => setChartData(res))
  }

  return (
    <div>
      <Header queryResultCallBack={queryResultCallBack} />
      <Ticker />
      <Content chartData={chartData} />
    </div>
  )
}

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
